_wandb:
    value:
        cli_version: 0.22.3
        e:
            hdsqj0wbvlxn4x26hjdwxvnmvl2tufwa:
                args:
                    - --env
                    - Acrobot-v1
                    - --algo
                    - DDQN
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "125900419072"
                        used: "125677395968"
                email: kareemmohamed1920@gmail.com
                executable: C:\Python313\python.exe
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-01dcbbd3-510e-6c05-8320-53c05c9581ae
                host: Karim
                memory:
                    total: "16913522688"
                os: Windows-11-10.0.22631-SP0
                program: C:\Users\karee\Desktop\RL_Assignment2\main.py
                python: CPython 3.13.1
                root: C:\Users\karee\Desktop\RL_Assignment2
                startedAt: "2025-11-11T14:57:14.215520Z"
                writerId: hdsqj0wbvlxn4x26hjdwxvnmvl2tufwa
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.1
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
algo:
    value: DDQN
batch_size:
    value: 128
env:
    value: Acrobot-v1
episodes:
    value: 600
epsilon_decay:
    value: 1000
epsilon_end:
    value: 0.05
epsilon_start:
    value: 0.9
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
memory_size:
    value: 10000
tau:
    value: 0.005
